export const SidebarPaths = [
  { title: "Debouncing", path: "/debouncing" },
  { title: "Infinite Scroll", path: "/infiniteScroll" },
  { title: "Tic Tac Toe", path: "/tictactoe" },
  { title: "Soduku Solver", path: "/sodukuSolver" },
  { title: "Higher Order Components", path: "/hoc" },
  { title: "Playground", path: "/playground" },
  { title: "Timer", path: "/timer" },
  { title: "Error Boundary", path: "/errorBoundary" },
  { title: "Context Api", path: "/contextApi" },
  { title: "Custom hooks", path: "/customHookUse" },
  { title: "Pagination", path: "/pagination" },
  { title: "File Structure", path: "/fileStructure" },
  { title: "Tabs", path: "/tabs" },
  { title: "Accordian", path: "/accordian" },
  { title: "Slider", path: "/slider" },
  { title: "Modal", path: "/modal" },
  { title: "Solid Principles", path: "/solid" },
  { title: "Star Rating", path: "/star" },
  { title: "Detect Outside", path: "/detectOutside" },
  { title: "Progress Bar", path: "/progressbar" },
  { title: "Toggle Switch", path: "/toggleSwitch" },
  { title: "Transfer List", path: "/transferList" },
  { title: "Nested Comments", path: "/nestedComments" }
];
